import random,tkinter,sys,os,getpass,spui
os.chdir('/home/'+getpass.getuser()+'/sanapeli/src')
base = spui.pohja()
base.configure(bg=spui.color1)
base.title("Sanapeli")
w = 15
f = tkinter.Frame(bg=spui.color2)
f.pack(side="left",anchor="n")
tippi = tkinter.Button(f,text="Tippi(paypall)",command=spui.callback,bg=spui.color2,width=w)
tippi.pack()
aiemmat = tkinter.Button(f,text="aiempien tulokset",command=spui.aiemmat,bg=spui.color2,width=w)
aiemmat.pack()
loppu = tkinter.Button(f,text="tallenna tulos",command=spui.tallenna,bg=spui.color2,width=w)
loppu.pack()
spui.seuraava()
base.mainloop()
