import random,tkinter,sys,os,getpass,spui
os.chdir('/home/'+getpass.getuser()+'/sanapeli/src')
base = spui.pohja()
base.configure(bg=spui.color1)
base.title("Sanapeli")
tippi = tkinter.Button(text="Tippi(paypall)",command=spui.callback,bg=spui.color2)
tippi.pack(side="left", anchor="nw")
spui.seuraava()
loppu = tkinter.Button(text="tallenna tulos",command=spui.tallenna,bg=spui.color2)
loppu.pack()
base.mainloop()
